#ifndef _EVENT_STATUS_HEADER_FILE_DEFINED
#define _EVENT_STATUS_HEADER_FILE_DEFINED

const ULONG S_PROCESSED=0x01000000;					//事件被正确的处理
const ULONG S_CANCELPROCESS=0x02000000;				//事件被处理，且无需发送给下一个对象
const ULONG S_CAPTURE=0x04000000;						//事件被处理, 获取接下去的所有事件
const ULONG S_RELEASECAPTURE=0x08000000;				//事件被处理, 不再截取后继事件

#endif //!define _EVENT_STATUS_HEADER_FILE_DEFINED
